apiVersion: v1
kind: Service
metadata:
  name: moodle
spec:
  type: NodePort
  selector:
    app: moodle
  ports:
    - port: {{.Values.moodle.service.portHttp}}
      targetPort: {{.Values.moodle.service.portHttp}}
      nodePort: {{.Values.moodle.service.nodePortHttp}}
