apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle
spec:
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
        - name: moodle
          image: {{.Values.moodle.image}}
          env:
            - name: SKIP_INSTALL
              value: 'false'
            - name: MOODLE_DATABASE_PASSWORD
              value: ''
            - name: MOODLE_WWWROOT
              value: 'http://localhost:30080'
          envFrom:
            - configMapRef:
                name: moodle-config
          ports:
            - containerPort: {{.Values.moodle.service.portHttp}}
          readinessProbe:
            httpGet:
              path: /
              port: {{.Values.moodle.service.portHttp}}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.moodle.service.portHttp}}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: moodle-code
              mountPath: /var/www/moodle
            - name: moodle-data
              mountPath: /var/www/moodledata
      volumes:
        - name: moodle-code
          persistentVolumeClaim:
            claimName: moodle-code
        - name: moodle-data
          persistentVolumeClaim:
            claimName: moodle-data
