mariadb:
  image: docker.io/bitnami/mariadb:latest
  host: mariadb
  database: moodle
  user: moodle_user
  charset: utf8mb4
  collate: utf8mb4_unicode_ci
  allowEmptyPassword: true
  storage: 8Gi
  service:
    port: 3306

moodle:
  image: docker.io/bentaylor0812/moodle:5.1.3_version3
  service:
    portHttp: 80
    portHttps: 8443
    nodePortHttp: 30080
    nodePortHttps: 30443
  databaseHost: mariadb
  databaseUser: moodle_user
  databaseName: moodle
  allowEmptyPassword: true
  storageMoodle: 5Gi
  storageMoodledata: 10Gi
  skipInstall: 'false'
